services:
  queue:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
  emergency-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=manusteril
  ward-db:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=manusteril